#!/bin/bash

# SE Exercise 1/2
#BASH

clear			# Clears screen
Usage() {
  echo $"$0 -c -w -e" 1>&2;
  echo $"memory_check Parameters: -c, Critical threshold; -w, Warning threshold; -e, Recipient mail address" 1>&2;
  exit 1;
}
#
#
#
# MAIN OPERATION
#
while getopts ":c:w:e:" opt;
  do
  case $opt in

    c)
      CRIT="$OPTARG"		# variable CRIT, critical threshold
      ;;
    w)
      WARN="$OPTARG"		# variable WARN, warning threshold
      ;;
    e)
      EMAIL="$OPTARG"		# variable EMAIL, recipient email address
      ;;
    \?)
      echo "Invalid parameter: -$OPTARG"		# if variable parameter was pressed
      Usage
      ;;
  esac
done
shift "$((OPTIND-1))"

# Checks if user provided the parameters and if critical threshold is greater than warning threshold
if [ -z "${CRIT}" ] || [ -z "${WARN}" ] || [ -z "${EMAIL}" ] || [ "${CRIT}" -lt "${WARN}" ];
then
  Usage
fi

free
TOTAL_MEMORY=$( free | grep Mem: | awk '{ print $2 }' )		# Grabs total memory value from free command
USED_MEMORY=$( free | grep Mem: | awk '{print $3}' )		# Grabs used memory value from free command
